<?php
/**
 * Module Name: phire-feed
 * Author: Nick Sagona
 * Description: This is the feed module for Phire CMS 2, to be used in conjunction with the Content and Media modules
 * Version: 1.0
 */
return [
    'phire-feed' => [
        'prefix' => 'Phire\Feed\\',
        'src'    => __DIR__ . '/../src',
        'routes' => include 'routes.php',
        'events' => [
            [
                'name'     => 'app.route.pre',
                'action'   => 'Phire\Feed\Event\Feed::bootstrap',
                'priority' => 1000
            ],
            [
                'name'     => 'app.send.pre',
                'action'   => 'Phire\Feed\Event\Feed::getAll',
                'priority' => 1000
            ],
            [
                'name'     => 'app.send.pre',
                'action'   => 'Phire\Feed\Event\Feed::save',
                'priority' => 1000
            ],
            [
                'name'     => 'app.send.pre',
                'action'   => 'Phire\Feed\Event\Feed::delete',
                'priority' => 1000
            ],
        ],
        'feed_type'    => 'rss',
        'feed_headers' => [
            'title'       => $_SERVER['HTTP_HOST'] . ' Feed',
            'link'        => 'http://' . $_SERVER['HTTP_HOST'] . BASE_PATH . '/feed',
            'description' => $_SERVER['HTTP_HOST'] . ' Feed, generated by Phire CMS',
            'author'      => 'Phire CMS',
            'pubDate'     => date('D, j M Y H:i:s O')
        ],
        'feed_limit'    => 25,
    ]
];
